- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
