- name: Deploy LEMP
  hosts: all
  become: yes
  vars_files:
    - vault.yaml
  tasks:
    - name: Debug user password
      debug:
        msg: "{{ mysql_root_password }} {{ mysql_user_password }}"
  roles:
    - nginx
    - php
    - mysql
    - initapps
    - joomla

