- name: Install unzip utility
  ansible.builtin.apt:
    name: unzip
    state: present
    update_cache: true

- name: Download joomla
  ansible.builtin.get_url:
    url: "{{ joomla_download_url }}"
    dest: /tmp/joomla.zip
    mode: '0644'

- name: Unzip joomla
  ansible.builtin.unarchive:
    src: /tmp/joomla.zip
    dest: /var/www/sites/joomla
    remote_src: true
    owner: www-data
    group: www-data

- name: Delete joomla zip file
  ansible.builtin.file:
    path: /tmp/joomla.zip
    state: absent
