- name: Install unzip utility
  ansible.builtin.apt:
    name: unzip
    state: present
    update_cache: true

- name: Download joomla
  ansible.builtin.get_url:
    url: "{{ joomla_download_url }}"
    dest: "{{ joomla_temp_dir }}"
    mode: "{{ default_file_mode }}"

- name: Unzip joomla
  ansible.builtin.unarchive:
    src: "{{ joomla_temp_dir }}"
    dest: "{{ path_joomla_site }}"
    remote_src: true
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"

- name: Delete joomla zip file
  ansible.builtin.file:
    path: "{{ joomla_temp_dir }}"
    state: absent
