- name: Remove default.conf
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ path_nginx_available_default_conf }}"
    - "{{ path_nginx_enabled_conf }}"

- name: Create Joomla directory
  ansible.builtin.file:
    path: "{{ path_joomla_site }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: '0755'

- name: Ensure permissions are set correctly
  ansible.builtin.file:
    path: "{{ path_joomla_site }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    recurse: true

- name: Create mysql user for joomla
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_user_password }}"
    priv: "{{ mysql_user_priv }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create mysql database for Joomla
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create joomla nginx configuration file
  ansible.builtin.template:
    src: joomla.conf.j2
    dest: "{{ path_nginx_available_joomla_conf }}"
    owner: root
    group: root
    mode: "{{ default_file_mode }}"
  notify: Restart nginx

- name: Create symbolic link for joomla site
  ansible.builtin.file:
    src: "{{ path_nginx_available_joomla_conf }}"
    dest: "{{ path_nginx_enabled_joomla_conf }}"
    state: link
  notify: Restart nginx
