- name: Install php and modules
  ansible.builtin.apt:
    name:
      - php"{{ php_version }}"
      - php"{{ php_version }}"-fpm
      - php"{{ php_version }}"-mysql
      - php"{{ php_version }}"-curl
      - php"{{ php_version }}"-gd
      - php"{{ php_version }}"-mbstring
      - php"{{ php_version }}"-xml
      - php"{{ php_version }}"-zip
    state: present
    update_cache: true

- name: Start and enable php
  ansible.builtin.service:
    name: php"{{ php_version }}"-fpm
    state: started
    enabled: true
