- name: Install php and modules
  ansible.builtin.apt:
    name:
      - php8.1
      - php8.1-fpm
      - php8.1-mysql
      - php8.1-curl
      - php8.1-gd
      - php8.1-mbstring
      - php8.1-xml
      - php8.1-zip
    state: present
    update_cache: true

- name: Start and enable php
  ansible.builtin.service:
    name: php8.1-fpm
    state: started
    enabled: true
